//! Toolkit-free client library — Principle VII conformance
//! fixture.
//!
//! The ONLY thing this crate is allowed to depend on, among
//! the display system, is `display-proto` — the shared wire
//! format. It deliberately does NOT depend on the `toolkit`
//! crate; the whole point of this fixture is to prove that
//! any client that can read `display-proto` can drive the
//! display server without a toolkit in the loop.
//!
//! The code below is intentionally direct: [`FreeClient`]
//! contains the hand-written request encoders and [`FreeSession`]
//! contains the small event-driven state machine used by the
//! standalone WASI binary. A reader who has just read
//! `specs/001-browser-os-v1/contracts/display-protocol.md`
//! should be able to map every transition to a wire message.
//!
//! Principle VII says "Protocol over API for the display
//! server — Wayland-inspired wire protocol, toolkit is a
//! library wrapper". The `tests/conformance.rs` integration
//! test pairs [`FreeSession`] against a real
//! `display_server::Server` over in-memory byte buffers and walks
//! discovery, role creation, painting, input, and close cleanup. The
//! standalone binary drives the same state machine over the PMos
//! `/run/display` fd; the browser integration gate proves that path in a
//! separately isolated Worker.

#![forbid(unsafe_code)]

use display_proto::events::{
    key_state, BufferRelease, CallbackDone, DisplayError, KeyboardKey, RegistryGlobal, ShmFormat,
    XdgToplevelClose, XdgToplevelConfigure,
};
use display_proto::ids::{IdAllocator, ObjectId};
use display_proto::wire::{MessageHeader, WireError, HEADER_SIZE};

/// `pmd_display.get_registry` opcode from the spec tables.
pub const OP_DISPLAY_GET_REGISTRY: u16 = 2;
pub const OP_DISPLAY_SYNC: u16 = 1;

/// `pmd_registry.bind` opcode.
pub const OP_REGISTRY_BIND: u16 = 1;

/// `pmd_compositor.create_surface` opcode.
pub const OP_COMPOSITOR_CREATE_SURFACE: u16 = 1;

/// `pmd_surface.commit` opcode.
pub const OP_SURFACE_COMMIT: u16 = 7;

/// `pmd_surface.attach` opcode.
pub const OP_SURFACE_ATTACH: u16 = 2;

/// `pmd_surface.damage` opcode.
pub const OP_SURFACE_DAMAGE: u16 = 3;

/// `pmd_shm.create_pool` opcode.
pub const OP_SHM_CREATE_POOL: u16 = 1;

/// `pmd_shm_pool.create_buffer` opcode.
pub const OP_SHM_POOL_CREATE_BUFFER: u16 = 1;

/// `pmd_shm_pool.destroy` opcode.
pub const OP_SHM_POOL_DESTROY: u16 = 3;

/// `pmd_shm_pool.write` opcode.
pub const OP_SHM_POOL_WRITE: u16 = 4;

/// `pmd_buffer.destroy` opcode.
pub const OP_BUFFER_DESTROY: u16 = 1;

/// `pmd_surface.destroy` opcode.
pub const OP_SURFACE_DESTROY: u16 = 1;

/// Shipped-v1 `pmd_xdg_shell.get_toplevel` opcode.
pub const OP_XDG_SHELL_GET_TOPLEVEL: u16 = 1;

/// `pmd_xdg_toplevel.set_title` opcode.
pub const OP_XDG_TOPLEVEL_SET_TITLE: u16 = 1;

/// `pmd_xdg_toplevel.set_app_id` opcode.
pub const OP_XDG_TOPLEVEL_SET_APP_ID: u16 = 2;

/// `pmd_xdg_toplevel.destroy` opcode.
pub const OP_XDG_TOPLEVEL_DESTROY: u16 = 3;

/// Shipped-v1 merged `pmd_xdg_toplevel.ack_configure` opcode.
pub const OP_XDG_TOPLEVEL_ACK_CONFIGURE: u16 = 4;

/// `pmd_seat.get_keyboard` opcode.
pub const OP_SEAT_GET_KEYBOARD: u16 = 2;

/// Fixed conformance-frame geometry from contract section 18.
pub const FRAME_WIDTH: u32 = 320;
pub const FRAME_HEIGHT: u32 = 200;
pub const FRAME_STRIDE: u32 = FRAME_WIDTH * 4;
pub const FRAME_BYTES: usize = FRAME_STRIDE as usize * FRAME_HEIGHT as usize;

/// Large, exact colour fields used as browser-visible conformance evidence.
pub const INITIAL_FRAME_RGBA: [u8; 4] = [0x19, 0xd3, 0xb3, 0xff];
pub const INPUT_FRAME_RGBA: [u8; 4] = [0xff, 0x8a, 0x1f, 0xff];
pub const FRAME_ACCENT_RGBA: [u8; 4] = [0x9b, 0x2c, 0xff, 0xff];

const SHM_WRITE_CHUNK_BYTES: usize = 24 * 1024;

/// Maximum byte slice offered to the production display socket in one event-
/// loop turn. It stays below the PMos syscall transport's 32 KiB heap window
/// and matches the largest inline pool-write request generated by this client.
pub const OUTBOUND_WRITE_MAX_BYTES: usize = 24 * 1024;

/// Errors the free client returns. A thin newtype over
/// [`WireError`] plus a few extra shapes the spec allows us
/// to produce without depending on `display_server`'s richer
/// `ClientError`.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum FreeClientError {
    /// Wire-format error forwarded from [`MessageHeader`].
    Wire(WireError),
    /// Client-side ID space exhausted.
    IdsExhausted,
}

impl From<WireError> for FreeClientError {
    fn from(e: WireError) -> Self {
        FreeClientError::Wire(e)
    }
}

/// A minimal hand-written client. Owns an odd-id allocator
/// and an outbound byte buffer; high-level helper methods
/// append framed messages to the buffer.
pub struct FreeClient {
    ids: IdAllocator,
    outbound: Vec<u8>,
}

impl Default for FreeClient {
    fn default() -> Self {
        FreeClient::new()
    }
}

impl FreeClient {
    pub fn new() -> Self {
        FreeClient {
            ids: IdAllocator::for_client(),
            outbound: Vec::new(),
        }
    }

    /// Allocate the next odd id in the client's partition.
    pub fn allocate_id(&mut self) -> Result<ObjectId, FreeClientError> {
        self.ids
            .allocate()
            .map_err(|_| FreeClientError::IdsExhausted)
    }

    /// How many bytes are queued for send.
    pub fn outbound_len(&self) -> usize {
        self.outbound.len()
    }

    /// Drain the outbound byte queue. The caller typically
    /// forwards these to a real transport OR feeds them to a
    /// paired server dispatcher in tests.
    pub fn drain_outbound(&mut self) -> Vec<u8> {
        core::mem::take(&mut self.outbound)
    }

    /// Append a framed request (header + payload) to the
    /// outbound queue. This is the low-level building block
    /// every helper below goes through — tests can use it
    /// directly to craft malformed requests for error-path
    /// coverage.
    pub fn encode_request(
        &mut self,
        object_id: ObjectId,
        opcode: u16,
        payload: &[u8],
    ) -> Result<(), FreeClientError> {
        let header = MessageHeader::try_new(object_id, opcode, payload.len(), 0)?;
        let start = self.outbound.len();
        self.outbound.resize(start + HEADER_SIZE, 0);
        header.encode(&mut self.outbound[start..start + HEADER_SIZE])?;
        self.outbound.extend_from_slice(payload);
        Ok(())
    }

    // ---- High-level helpers ------------------------------------
    //
    // Each helper reads like the spec's request table row: it
    // lists the opcode number, the argument layout, and emits
    // the framed bytes. No shared state: a reader can map each
    // method back to the spec in seconds.

    /// `pmd_display.get_registry(new_id)` — spec §3 row 2.
    /// Payload: a single 4-byte little-endian `new_id`.
    /// Returns the allocated registry id.
    pub fn get_registry(&mut self) -> Result<ObjectId, FreeClientError> {
        let registry_id = self.allocate_id()?;
        let payload = registry_id.raw().to_le_bytes();
        self.encode_request(ObjectId::DISPLAY, OP_DISPLAY_GET_REGISTRY, &payload)?;
        Ok(registry_id)
    }

    /// `pmd_display.sync(new_id)` — explicit ordering marker used to delimit
    /// the registry catalog independently of transport read boundaries.
    pub fn sync(&mut self) -> Result<ObjectId, FreeClientError> {
        let callback_id = self.allocate_id()?;
        self.encode_request(
            ObjectId::DISPLAY,
            OP_DISPLAY_SYNC,
            &callback_id.raw().to_le_bytes(),
        )?;
        Ok(callback_id)
    }

    /// `pmd_registry.bind(name, interface, version, new_id)` —
    /// spec §4 row 1. Payload: u32 name, length-prefixed
    /// string, u32 version, u32 new_id. Returns the allocated
    /// new_id.
    pub fn registry_bind(
        &mut self,
        registry_id: ObjectId,
        global_name: u32,
        interface_name: &str,
        version: u32,
    ) -> Result<ObjectId, FreeClientError> {
        let new_id = self.allocate_id()?;
        let mut payload = Vec::new();
        payload.extend_from_slice(&global_name.to_le_bytes());
        append_wire_string(&mut payload, interface_name);
        payload.extend_from_slice(&version.to_le_bytes());
        payload.extend_from_slice(&new_id.raw().to_le_bytes());
        self.encode_request(registry_id, OP_REGISTRY_BIND, &payload)?;
        Ok(new_id)
    }

    /// `pmd_compositor.create_surface(new_id)` — spec §5.
    pub fn compositor_create_surface(
        &mut self,
        compositor_id: ObjectId,
    ) -> Result<ObjectId, FreeClientError> {
        let new_id = self.allocate_id()?;
        self.encode_request(
            compositor_id,
            OP_COMPOSITOR_CREATE_SURFACE,
            &new_id.raw().to_le_bytes(),
        )?;
        Ok(new_id)
    }

    /// `pmd_shm.create_pool(new_id, size)` — shipped v1 uses the documented
    /// inline `pmd_shm_pool.write` transport instead of passing a SAB fd.
    pub fn shm_create_pool(
        &mut self,
        shm_id: ObjectId,
        size: u32,
    ) -> Result<ObjectId, FreeClientError> {
        let pool_id = self.allocate_id()?;
        let mut payload = [0u8; 8];
        payload[0..4].copy_from_slice(&pool_id.raw().to_le_bytes());
        payload[4..8].copy_from_slice(&size.to_le_bytes());
        self.encode_request(shm_id, OP_SHM_CREATE_POOL, &payload)?;
        Ok(pool_id)
    }

    /// `pmd_shm_pool.create_buffer(new_id, offset, width, height, stride,
    /// format)` — spec section 7.
    pub fn shm_pool_create_buffer(
        &mut self,
        pool_id: ObjectId,
        offset: u32,
        width: u32,
        height: u32,
        stride: u32,
        format: u32,
    ) -> Result<ObjectId, FreeClientError> {
        let buffer_id = self.allocate_id()?;
        let mut payload = [0u8; 24];
        payload[0..4].copy_from_slice(&buffer_id.raw().to_le_bytes());
        payload[4..8].copy_from_slice(&offset.to_le_bytes());
        payload[8..12].copy_from_slice(&width.to_le_bytes());
        payload[12..16].copy_from_slice(&height.to_le_bytes());
        payload[16..20].copy_from_slice(&stride.to_le_bytes());
        payload[20..24].copy_from_slice(&format.to_le_bytes());
        self.encode_request(pool_id, OP_SHM_POOL_CREATE_BUFFER, &payload)?;
        Ok(buffer_id)
    }

    /// Upload one contiguous range into a shipped-v1 shm pool. Callers split
    /// full frames so every message stays below the 16-bit wire length.
    pub fn shm_pool_write(
        &mut self,
        pool_id: ObjectId,
        offset: u32,
        bytes: &[u8],
    ) -> Result<(), FreeClientError> {
        let mut payload = Vec::with_capacity(4 + bytes.len());
        payload.extend_from_slice(&offset.to_le_bytes());
        payload.extend_from_slice(bytes);
        self.encode_request(pool_id, OP_SHM_POOL_WRITE, &payload)
    }

    /// Retire a pool object after its buffers and surfaces have been retired.
    pub fn shm_pool_destroy(&mut self, pool_id: ObjectId) -> Result<(), FreeClientError> {
        self.encode_request(pool_id, OP_SHM_POOL_DESTROY, &[])
    }

    /// Retire a buffer object.
    pub fn buffer_destroy(&mut self, buffer_id: ObjectId) -> Result<(), FreeClientError> {
        self.encode_request(buffer_id, OP_BUFFER_DESTROY, &[])
    }

    /// Retire a roleless surface object.
    pub fn surface_destroy(&mut self, surface_id: ObjectId) -> Result<(), FreeClientError> {
        self.encode_request(surface_id, OP_SURFACE_DESTROY, &[])
    }

    /// Shipped-v1 `pmd_xdg_shell.get_toplevel(new_id, surface_id)`. The v1
    /// wire protocol deliberately collapses the canonical xdg-surface
    /// intermediate into this request.
    pub fn xdg_shell_get_toplevel(
        &mut self,
        xdg_shell_id: ObjectId,
        surface_id: ObjectId,
    ) -> Result<ObjectId, FreeClientError> {
        let toplevel_id = self.allocate_id()?;
        let mut payload = [0u8; 8];
        payload[0..4].copy_from_slice(&toplevel_id.raw().to_le_bytes());
        payload[4..8].copy_from_slice(&surface_id.raw().to_le_bytes());
        self.encode_request(xdg_shell_id, OP_XDG_SHELL_GET_TOPLEVEL, &payload)?;
        Ok(toplevel_id)
    }

    pub fn xdg_toplevel_set_title(
        &mut self,
        toplevel_id: ObjectId,
        title: &str,
    ) -> Result<(), FreeClientError> {
        let mut payload = Vec::new();
        append_wire_string(&mut payload, title);
        self.encode_request(toplevel_id, OP_XDG_TOPLEVEL_SET_TITLE, &payload)
    }

    pub fn xdg_toplevel_set_app_id(
        &mut self,
        toplevel_id: ObjectId,
        app_id: &str,
    ) -> Result<(), FreeClientError> {
        let mut payload = Vec::new();
        append_wire_string(&mut payload, app_id);
        self.encode_request(toplevel_id, OP_XDG_TOPLEVEL_SET_APP_ID, &payload)
    }

    pub fn xdg_toplevel_ack_configure(
        &mut self,
        toplevel_id: ObjectId,
        serial: u32,
    ) -> Result<(), FreeClientError> {
        self.encode_request(
            toplevel_id,
            OP_XDG_TOPLEVEL_ACK_CONFIGURE,
            &serial.to_le_bytes(),
        )
    }

    pub fn xdg_toplevel_destroy(&mut self, toplevel_id: ObjectId) -> Result<(), FreeClientError> {
        self.encode_request(toplevel_id, OP_XDG_TOPLEVEL_DESTROY, &[])
    }

    /// `pmd_seat.get_keyboard(new_id)` — creates the ordinary-client keyboard
    /// event object used by the browser input proof.
    pub fn seat_get_keyboard(&mut self, seat_id: ObjectId) -> Result<ObjectId, FreeClientError> {
        let keyboard_id = self.allocate_id()?;
        self.encode_request(
            seat_id,
            OP_SEAT_GET_KEYBOARD,
            &keyboard_id.raw().to_le_bytes(),
        )?;
        Ok(keyboard_id)
    }

    /// `pmd_surface.attach(buffer_id, x, y)` — spec §9 row 2.
    /// Payload: u32 buffer_id, i32 x, i32 y.
    pub fn surface_attach(
        &mut self,
        surface_id: ObjectId,
        buffer_id: ObjectId,
        x: i32,
        y: i32,
    ) -> Result<(), FreeClientError> {
        let mut payload = [0u8; 12];
        payload[0..4].copy_from_slice(&buffer_id.raw().to_le_bytes());
        payload[4..8].copy_from_slice(&x.to_le_bytes());
        payload[8..12].copy_from_slice(&y.to_le_bytes());
        self.encode_request(surface_id, OP_SURFACE_ATTACH, &payload)
    }

    /// `pmd_surface.damage(x, y, w, h)` — spec §9 row 3.
    pub fn surface_damage(
        &mut self,
        surface_id: ObjectId,
        x: i32,
        y: i32,
        w: i32,
        h: i32,
    ) -> Result<(), FreeClientError> {
        let mut payload = [0u8; 16];
        payload[0..4].copy_from_slice(&x.to_le_bytes());
        payload[4..8].copy_from_slice(&y.to_le_bytes());
        payload[8..12].copy_from_slice(&w.to_le_bytes());
        payload[12..16].copy_from_slice(&h.to_le_bytes());
        self.encode_request(surface_id, OP_SURFACE_DAMAGE, &payload)
    }

    /// `pmd_surface.commit()` — spec §9 row 7. No payload.
    pub fn surface_commit(&mut self, surface_id: ObjectId) -> Result<(), FreeClientError> {
        self.encode_request(surface_id, OP_SURFACE_COMMIT, &[])
    }

    /// Parse the next framed message from the front of
    /// `bytes`. Returns the header and the number of bytes
    /// consumed, or `None` if `bytes` doesn't contain a
    /// complete message yet. Wire-format errors surface as
    /// `Some(Err(...))`.
    ///
    /// A buffer shorter than the header, OR a buffer whose
    /// header is structurally valid but claims more bytes
    /// than are available, is "need more bytes" → `None`.
    /// Only structurally-invalid headers (length below
    /// `HEADER_SIZE`, reserved byte set) produce an error.
    pub fn try_decode_event(bytes: &[u8]) -> Option<Result<(MessageHeader, usize), WireError>> {
        if bytes.len() < HEADER_SIZE {
            return None;
        }
        // Peek the length field (bytes 6..8) without running
        // the full decode: short buffers should read as
        // "need more bytes" (None), not as InvalidLength
        // errors.
        let claimed_length = u16::from_le_bytes([bytes[6], bytes[7]]) as usize;
        if claimed_length < HEADER_SIZE {
            return Some(Err(WireError::InvalidLength));
        }
        if bytes.len() < claimed_length {
            return None;
        }
        match MessageHeader::decode(bytes) {
            Ok(header) => Some(Ok((header, header.length as usize))),
            Err(e) => Some(Err(e)),
        }
    }
}

/// Append a length-prefixed, 4-byte-aligned UTF-8 string to
/// `out` as the spec's §1 framing describes.
///
/// Layout: `u32 byte_length`, `byte_length` bytes of UTF-8,
/// then padding to the next 4-byte boundary with zeros.
pub fn append_wire_string(out: &mut Vec<u8>, s: &str) {
    let bytes = s.as_bytes();
    let len = bytes.len() as u32;
    out.extend_from_slice(&len.to_le_bytes());
    out.extend_from_slice(bytes);
    let pad = (4 - (bytes.len() % 4)) % 4;
    for _ in 0..pad {
        out.push(0);
    }
}

/// One complete event frame decoded from the byte stream. Object-interface
/// interpretation remains in [`FreeSession`], keeping this wire helper usable
/// without the toolkit's client object table.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RawEvent {
    pub header: MessageHeader,
    pub payload: Vec<u8>,
}

/// High-level progress emitted by the standalone conformance session.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SessionSignal {
    GlobalsBound,
    Configured {
        serial: u32,
        width: i32,
        height: i32,
    },
    FramePresented {
        input_response: bool,
    },
    Key {
        key: u32,
        state: u32,
    },
    BufferReleased(ObjectId),
    CloseRequested,
}

/// Errors that make a raw protocol session unsafe to continue.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SessionError {
    Client(FreeClientError),
    MalformedEvent(&'static str),
    Server {
        object_id: ObjectId,
        code: u32,
        message: String,
    },
    InvalidState(&'static str),
}

impl From<FreeClientError> for SessionError {
    fn from(error: FreeClientError) -> Self {
        SessionError::Client(error)
    }
}

/// Object ids allocated by the raw client during a production session.
/// Keeping these public makes the native server-isolation test able to inject
/// configure, input, and close events without importing toolkit state.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SessionObjects {
    pub compositor: Option<ObjectId>,
    pub shm: Option<ObjectId>,
    pub xdg_shell: Option<ObjectId>,
    pub seat: Option<ObjectId>,
    pub keyboard: Option<ObjectId>,
    pub surface: Option<ObjectId>,
    pub toplevel: Option<ObjectId>,
    pub pool: Option<ObjectId>,
    pub buffers: [Option<ObjectId>; 2],
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
struct PendingFrame {
    surface: ObjectId,
    buffer: ObjectId,
    input_response: bool,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
enum OutboundCompletion {
    Plain,
    FrameUpload(PendingFrame),
    FrameCommit { input_response: bool },
    Shutdown,
}

/// Complete toolkit-free display session used by the WASI binary and native
/// conformance gate. It discovers globals from registry events rather than
/// assuming server-assigned names, speaks only framed display messages, and
/// never reaches display-server or toolkit APIs.
pub struct FreeSession {
    client: FreeClient,
    registry: ObjectId,
    catalog_callback: ObjectId,
    catalog_complete: bool,
    globals: Vec<RegistryGlobal>,
    objects: SessionObjects,
    inbound: Vec<u8>,
    configured: bool,
    presented: bool,
    initial_frame_queued: bool,
    input_repainted: bool,
    input_frame_queued: bool,
    close_requested: bool,
    shutdown_queued: bool,
    shutdown_complete: bool,
    queued_completion: Option<OutboundCompletion>,
    in_flight_completion: Option<OutboundCompletion>,
}

impl FreeSession {
    /// Queue the initial `pmd_display.get_registry` request.
    pub fn new() -> Result<Self, SessionError> {
        let mut client = FreeClient::new();
        let registry = client.get_registry()?;
        let catalog_callback = client.sync()?;
        Ok(Self {
            client,
            registry,
            catalog_callback,
            catalog_complete: false,
            globals: Vec::new(),
            objects: SessionObjects::default(),
            inbound: Vec::with_capacity(64 * 1024),
            configured: false,
            presented: false,
            initial_frame_queued: false,
            input_repainted: false,
            input_frame_queued: false,
            close_requested: false,
            shutdown_queued: false,
            shutdown_complete: false,
            queued_completion: Some(OutboundCompletion::Plain),
            in_flight_completion: None,
        })
    }

    pub fn registry_id(&self) -> ObjectId {
        self.registry
    }

    pub fn objects(&self) -> &SessionObjects {
        &self.objects
    }

    pub fn is_configured(&self) -> bool {
        self.configured
    }

    pub fn is_presented(&self) -> bool {
        self.presented
    }

    pub fn input_repainted(&self) -> bool {
        self.input_repainted
    }

    pub fn close_requested(&self) -> bool {
        self.close_requested
    }

    /// True only after the ordered destroy batch has been accepted by the
    /// display socket. Seeing `xdg_toplevel.close` alone is not sufficient for
    /// the standalone process to exit without truncating teardown requests.
    pub fn shutdown_complete(&self) -> bool {
        self.shutdown_complete
    }

    pub fn outbound_len(&self) -> usize {
        self.client.outbound_len()
    }

    fn has_outbound(&self) -> bool {
        self.client.outbound_len() > 0 || self.in_flight_completion.is_some()
    }

    fn take_outbound(&mut self) -> Result<Option<Vec<u8>>, SessionError> {
        if self.in_flight_completion.is_some() {
            return Ok(None);
        }
        if self.client.outbound_len() == 0 {
            return Ok(None);
        }
        let completion = self
            .queued_completion
            .take()
            .ok_or(SessionError::InvalidState(
                "outbound batch has no completion",
            ))?;
        self.in_flight_completion = Some(completion);
        Ok(Some(self.client.drain_outbound()))
    }

    fn complete_outbound(&mut self) -> Result<Vec<SessionSignal>, SessionError> {
        let completion = self
            .in_flight_completion
            .take()
            .ok_or(SessionError::InvalidState("no outbound batch is in flight"))?;
        let mut signals = Vec::new();
        match completion {
            OutboundCompletion::Plain => {}
            OutboundCompletion::FrameUpload(frame) => {
                self.client
                    .surface_attach(frame.surface, frame.buffer, 0, 0)?;
                self.client.surface_damage(
                    frame.surface,
                    0,
                    0,
                    FRAME_WIDTH as i32,
                    FRAME_HEIGHT as i32,
                )?;
                self.client.surface_commit(frame.surface)?;
                self.queued_completion = Some(OutboundCompletion::FrameCommit {
                    input_response: frame.input_response,
                });
            }
            OutboundCompletion::FrameCommit { input_response } => {
                if input_response {
                    self.input_frame_queued = false;
                    self.input_repainted = true;
                } else {
                    self.initial_frame_queued = false;
                    self.presented = true;
                }
                signals.push(SessionSignal::FramePresented { input_response });
            }
            OutboundCompletion::Shutdown => {
                self.shutdown_complete = true;
            }
        }
        self.queue_shutdown_if_ready()?;
        Ok(signals)
    }

    fn set_queued_completion(
        &mut self,
        completion: OutboundCompletion,
    ) -> Result<(), SessionError> {
        match self.queued_completion {
            None | Some(OutboundCompletion::Plain) => {
                self.queued_completion = Some(completion);
                Ok(())
            }
            Some(_) => Err(SessionError::InvalidState(
                "overlapping outbound protocol phases",
            )),
        }
    }

    /// Names still missing from the production-v1 registry bootstrap.
    pub fn missing_required_globals(&self) -> Vec<&'static str> {
        ["pmd_compositor", "pmd_shm", "pmd_xdg_shell", "pmd_seat"]
            .into_iter()
            .filter(|name| !self.globals.iter().any(|global| global.interface == *name))
            .collect()
    }

    /// Append transport bytes, retain any partial trailing frame, process all
    /// complete events, and queue protocol responses for [`SessionDriver`].
    pub fn push_server_bytes(&mut self, bytes: &[u8]) -> Result<Vec<SessionSignal>, SessionError> {
        self.inbound.extend_from_slice(bytes);
        let mut events = Vec::new();
        let mut consumed = 0usize;
        loop {
            let remaining = &self.inbound[consumed..];
            let Some(decoded) = FreeClient::try_decode_event(remaining) else {
                break;
            };
            let (header, length) = decoded.map_err(FreeClientError::Wire)?;
            events.push(RawEvent {
                header,
                payload: remaining[HEADER_SIZE..length].to_vec(),
            });
            consumed += length;
        }
        if consumed > 0 {
            self.inbound.drain(..consumed);
        }

        let mut signals = Vec::new();
        for event in events {
            self.handle_event(event, &mut signals)?;
        }
        if self.maybe_bind_globals_and_create_role()? {
            signals.push(SessionSignal::GlobalsBound);
        }
        Ok(signals)
    }

    fn handle_event(
        &mut self,
        event: RawEvent,
        signals: &mut Vec<SessionSignal>,
    ) -> Result<(), SessionError> {
        let object_id = event.header.object_id;
        let opcode = event.header.opcode;

        if object_id == ObjectId::DISPLAY && opcode == 1 {
            let error = DisplayError::decode(&event.payload)
                .map_err(|_| SessionError::MalformedEvent("pmd_display.error"))?;
            return Err(SessionError::Server {
                object_id: error.object_id,
                code: error.code,
                message: error.message,
            });
        }

        if object_id == self.catalog_callback && opcode == 1 {
            CallbackDone::decode(&event.payload)
                .map_err(|_| SessionError::MalformedEvent("pmd_callback.done"))?;
            self.catalog_complete = true;
            return Ok(());
        }

        if object_id == self.registry && opcode == 1 {
            let global = RegistryGlobal::decode(&event.payload)
                .map_err(|_| SessionError::MalformedEvent("pmd_registry.global"))?;
            if !self
                .globals
                .iter()
                .any(|known| known.interface == global.interface)
            {
                self.globals.push(global);
            }
            return Ok(());
        }

        if Some(object_id) == self.objects.shm && opcode == 1 {
            ShmFormat::decode(&event.payload)
                .map_err(|_| SessionError::MalformedEvent("pmd_shm.format"))?;
            return Ok(());
        }

        if Some(object_id) == self.objects.toplevel {
            match opcode {
                1 => {
                    let configure = XdgToplevelConfigure::decode(&event.payload)
                        .map_err(|_| SessionError::MalformedEvent("pmd_xdg_toplevel.configure"))?;
                    self.client
                        .xdg_toplevel_ack_configure(object_id, configure.serial)?;
                    self.ensure_plain_outbound_completion();
                    self.configured = true;
                    signals.push(SessionSignal::Configured {
                        serial: configure.serial,
                        width: configure.width,
                        height: configure.height,
                    });
                    if !self.presented && !self.initial_frame_queued {
                        self.create_buffers_and_present_initial_frame()?;
                        self.initial_frame_queued = true;
                    }
                }
                2 => {
                    XdgToplevelClose::decode(&event.payload)
                        .map_err(|_| SessionError::MalformedEvent("pmd_xdg_toplevel.close"))?;
                    self.close_requested = true;
                    signals.push(SessionSignal::CloseRequested);
                    self.queue_shutdown_if_ready()?;
                }
                _ => {}
            }
            return Ok(());
        }

        if Some(object_id) == self.objects.keyboard && opcode == 1 {
            let key = KeyboardKey::decode(&event.payload)
                .map_err(|_| SessionError::MalformedEvent("pmd_keyboard.key"))?;
            signals.push(SessionSignal::Key {
                key: key.key,
                state: key.state,
            });
            if key.state == key_state::PRESSED
                && Some(key.surface_id) == self.objects.surface
                && self.presented
                && !self.input_repainted
                && !self.input_frame_queued
                && !self.close_requested
            {
                self.queue_frame(1, true)?;
                self.input_frame_queued = true;
            }
            return Ok(());
        }

        for buffer_id in self.objects.buffers.into_iter().flatten() {
            if object_id == buffer_id && opcode == 1 {
                BufferRelease::decode(&event.payload)
                    .map_err(|_| SessionError::MalformedEvent("pmd_buffer.release"))?;
                signals.push(SessionSignal::BufferReleased(buffer_id));
                break;
            }
        }
        Ok(())
    }

    fn maybe_bind_globals_and_create_role(&mut self) -> Result<bool, SessionError> {
        if self.objects.toplevel.is_some() || !self.catalog_complete {
            return Ok(false);
        }
        let Some((compositor_name, compositor_version)) = self.global("pmd_compositor") else {
            return Ok(false);
        };
        let Some((shm_name, shm_version)) = self.global("pmd_shm") else {
            return Ok(false);
        };
        let Some((xdg_name, xdg_version)) = self.global("pmd_xdg_shell") else {
            return Ok(false);
        };
        let Some((seat_name, seat_version)) = self.global("pmd_seat") else {
            return Ok(false);
        };

        let compositor = self.client.registry_bind(
            self.registry,
            compositor_name,
            "pmd_compositor",
            compositor_version.min(1),
        )?;
        let shm =
            self.client
                .registry_bind(self.registry, shm_name, "pmd_shm", shm_version.min(1))?;
        let xdg_shell = self.client.registry_bind(
            self.registry,
            xdg_name,
            "pmd_xdg_shell",
            xdg_version.min(1),
        )?;
        let seat =
            self.client
                .registry_bind(self.registry, seat_name, "pmd_seat", seat_version.min(1))?;
        let keyboard = self.client.seat_get_keyboard(seat)?;
        let surface = self.client.compositor_create_surface(compositor)?;
        let toplevel = self.client.xdg_shell_get_toplevel(xdg_shell, surface)?;
        self.client
            .xdg_toplevel_set_title(toplevel, "Raw Protocol Window")?;
        self.client
            .xdg_toplevel_set_app_id(toplevel, "pmos.toolkit-free-client")?;
        self.client.surface_commit(surface)?;
        self.objects.compositor = Some(compositor);
        self.objects.shm = Some(shm);
        self.objects.xdg_shell = Some(xdg_shell);
        self.objects.seat = Some(seat);
        self.objects.keyboard = Some(keyboard);
        self.objects.surface = Some(surface);
        self.objects.toplevel = Some(toplevel);
        self.set_queued_completion(OutboundCompletion::Plain)?;
        Ok(true)
    }

    fn global(&self, interface: &str) -> Option<(u32, u32)> {
        self.globals
            .iter()
            .find(|global| global.interface == interface)
            .map(|global| (global.name, global.version))
    }

    fn create_buffers_and_present_initial_frame(&mut self) -> Result<(), SessionError> {
        let shm = self
            .objects
            .shm
            .ok_or(SessionError::InvalidState("shm global is not bound"))?;
        let pool_size = u32::try_from(FRAME_BYTES * 2)
            .map_err(|_| SessionError::InvalidState("frame pool overflows u32"))?;
        let pool = self.client.shm_create_pool(shm, pool_size)?;
        let first = self.client.shm_pool_create_buffer(
            pool,
            0,
            FRAME_WIDTH,
            FRAME_HEIGHT,
            FRAME_STRIDE,
            ShmFormat::FORMAT_ARGB8888,
        )?;
        let second = self.client.shm_pool_create_buffer(
            pool,
            FRAME_BYTES as u32,
            FRAME_WIDTH,
            FRAME_HEIGHT,
            FRAME_STRIDE,
            ShmFormat::FORMAT_ARGB8888,
        )?;
        self.objects.pool = Some(pool);
        self.objects.buffers = [Some(first), Some(second)];
        self.queue_frame(0, false)
    }

    fn queue_frame(
        &mut self,
        buffer_index: usize,
        input_response: bool,
    ) -> Result<(), SessionError> {
        let pool = self
            .objects
            .pool
            .ok_or(SessionError::InvalidState("shm pool is not allocated"))?;
        let buffer = self
            .objects
            .buffers
            .get(buffer_index)
            .copied()
            .flatten()
            .ok_or(SessionError::InvalidState("frame buffer is not allocated"))?;
        let surface = self
            .objects
            .surface
            .ok_or(SessionError::InvalidState("surface is not allocated"))?;
        let pixels = conformance_frame(input_response);
        let base_offset = buffer_index * FRAME_BYTES;
        for (chunk_index, chunk) in pixels.chunks(SHM_WRITE_CHUNK_BYTES).enumerate() {
            let relative = chunk_index * SHM_WRITE_CHUNK_BYTES;
            self.client
                .shm_pool_write(pool, (base_offset + relative) as u32, chunk)?;
        }
        self.set_queued_completion(OutboundCompletion::FrameUpload(PendingFrame {
            surface,
            buffer,
            input_response,
        }))
    }

    fn queue_clean_shutdown(&mut self) -> Result<(), SessionError> {
        if self.shutdown_queued || self.shutdown_complete {
            return Ok(());
        }
        if let Some(toplevel) = self.objects.toplevel {
            self.client.xdg_toplevel_destroy(toplevel)?;
        }
        if let Some(surface) = self.objects.surface {
            self.client.surface_destroy(surface)?;
        }
        for buffer in self.objects.buffers.into_iter().flatten() {
            self.client.buffer_destroy(buffer)?;
        }
        if let Some(pool) = self.objects.pool {
            self.client.shm_pool_destroy(pool)?;
        }
        self.shutdown_queued = true;
        if self.client.outbound_len() == 0 {
            self.shutdown_complete = true;
        } else {
            self.set_queued_completion(OutboundCompletion::Shutdown)?;
        }
        Ok(())
    }

    fn queue_shutdown_if_ready(&mut self) -> Result<(), SessionError> {
        if !self.close_requested
            || self.shutdown_queued
            || self.shutdown_complete
            || self.in_flight_completion.is_some()
            || self.queued_completion.is_some()
            || self.client.outbound_len() > 0
        {
            return Ok(());
        }
        self.queue_clean_shutdown()
    }

    fn ensure_plain_outbound_completion(&mut self) {
        // A configure can arrive while an earlier frame phase is in flight.
        // Its ACK then starts the next outbound batch and needs its own tag.
        if self.queued_completion.is_none() {
            self.queued_completion = Some(OutboundCompletion::Plain);
        }
    }
}

/// Result of one production-shaped socket write attempt.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum WriteAttempt {
    /// The socket accepted exactly this many bytes from the offered prefix.
    Written(usize),
    /// The non-blocking socket reported `EAGAIN` without consuming bytes.
    WouldBlock,
    /// Any non-`EAGAIN` WASI errno.
    Failed(i32),
}

/// Fatal errors from the bounded outbound driver.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SessionDriverError {
    Session(SessionError),
    Transport(i32),
    ZeroProgress,
    InvalidWriteCount { written: usize, offered: usize },
}

impl From<SessionError> for SessionDriverError {
    fn from(error: SessionError) -> Self {
        Self::Session(error)
    }
}

/// Observable result of one outer-loop write turn.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct OutboundTurn {
    pub attempted: bool,
    pub written: usize,
    pub pending: bool,
    pub signals: Vec<SessionSignal>,
}

/// Couples [`FreeSession`] protocol phases to one resumable byte suffix. The
/// caller invokes [`Self::write_turn`] at most once per GUI-loop turn and polls
/// for display writability only whenever [`Self::wants_write`] remains true,
/// returning to readability after the exact suffix drains.
pub struct SessionDriver {
    session: FreeSession,
    bytes: Vec<u8>,
    offset: usize,
}

impl SessionDriver {
    pub fn new() -> Result<Self, SessionError> {
        Ok(Self::from_session(FreeSession::new()?))
    }

    pub fn from_session(session: FreeSession) -> Self {
        Self {
            session,
            bytes: Vec::new(),
            offset: 0,
        }
    }

    pub fn session(&self) -> &FreeSession {
        &self.session
    }

    pub fn push_server_bytes(&mut self, bytes: &[u8]) -> Result<Vec<SessionSignal>, SessionError> {
        self.session.push_server_bytes(bytes)
    }

    pub fn wants_write(&self) -> bool {
        self.offset < self.bytes.len() || self.session.has_outbound()
    }

    pub fn shutdown_complete(&self) -> bool {
        self.session.shutdown_complete()
    }

    /// Offer at most [`OUTBOUND_WRITE_MAX_BYTES`] to exactly one caller-
    /// supplied `fd_write` attempt. Partial writes retain the unwritten suffix;
    /// `WouldBlock` retains the complete offered prefix. A completed upload
    /// phase queues attach/damage/commit for a later call, never the same turn.
    pub fn write_turn<F>(&mut self, write: F) -> Result<OutboundTurn, SessionDriverError>
    where
        F: FnOnce(&[u8]) -> WriteAttempt,
    {
        if self.offset == self.bytes.len() {
            self.bytes.clear();
            self.offset = 0;
            if let Some(bytes) = self.session.take_outbound()? {
                self.bytes = bytes;
            }
        }

        if self.bytes.is_empty() {
            return Ok(OutboundTurn {
                pending: self.wants_write(),
                ..OutboundTurn::default()
            });
        }

        let end = (self.offset + OUTBOUND_WRITE_MAX_BYTES).min(self.bytes.len());
        let offered = &self.bytes[self.offset..end];
        let offered_len = offered.len();
        let written = match write(offered) {
            WriteAttempt::Written(0) => return Err(SessionDriverError::ZeroProgress),
            WriteAttempt::Written(written) if written <= offered_len => written,
            WriteAttempt::Written(written) => {
                return Err(SessionDriverError::InvalidWriteCount {
                    written,
                    offered: offered_len,
                })
            }
            WriteAttempt::WouldBlock => {
                return Ok(OutboundTurn {
                    attempted: true,
                    pending: true,
                    ..OutboundTurn::default()
                })
            }
            WriteAttempt::Failed(errno) => return Err(SessionDriverError::Transport(errno)),
        };
        self.offset += written;

        let signals = if self.offset == self.bytes.len() {
            self.bytes.clear();
            self.offset = 0;
            self.session.complete_outbound()?
        } else {
            Vec::new()
        };

        Ok(OutboundTurn {
            attempted: true,
            written,
            pending: self.wants_write(),
            signals,
        })
    }
}

/// Build the exact 320x200 RGBA frame sent by the raw client. The broad solid
/// field is easy to identify in browser framebuffer pixels, while the accent
/// border and corner marker prove the bounded surface was composed rather
/// than a single coincidental pixel matching another application.
pub fn conformance_frame(input_response: bool) -> Vec<u8> {
    let fill = if input_response {
        INPUT_FRAME_RGBA
    } else {
        INITIAL_FRAME_RGBA
    };
    let mut pixels = vec![0u8; FRAME_BYTES];
    for pixel in pixels.chunks_exact_mut(4) {
        pixel.copy_from_slice(&fill);
    }
    for y in 0..FRAME_HEIGHT as usize {
        for x in 0..FRAME_WIDTH as usize {
            let border =
                x < 8 || y < 8 || x >= FRAME_WIDTH as usize - 8 || y >= FRAME_HEIGHT as usize - 8;
            let marker = (24..72).contains(&x) && (24..72).contains(&y) && (x + y) % 8 < 4;
            if border || marker {
                let offset = (y * FRAME_WIDTH as usize + x) * 4;
                pixels[offset..offset + 4].copy_from_slice(&FRAME_ACCENT_RGBA);
            }
        }
    }
    pixels
}
