[boot]
display_server = "/usr/bin/display-server"
shell          = "/usr/bin/shell"
autostart      = []

[capabilities.display-server]
grant = ["DISPLAY_SERVER", "DEV_BLOCK"]

[capabilities.shell]
grant = ["DISPLAY_CLIENT", "SHELL", "PROC_ENUMERATE", "KEYMAP_ADMIN"]

[capabilities.sysmon]
grant = ["DISPLAY_CLIENT", "PROC_ENUMERATE", "PROC_KILL_ANY"]

[env]
PATH            = "/bin:/usr/bin"
HOME            = "/home/user"
USER            = "user"
XDG_RUNTIME_DIR = "/run"
PMOS_DISPLAY    = "/run/display"

[debug]
kernel_log_level = "info"
serial_shell     = false
