// AUTOGENERATED by `cargo run -p xtask -- gen-sab-layout`.
// Do not edit by hand. Source of truth is the `abi` crate
// (crates/abi/src/ring.rs and crates/abi/src/version.rs).
//
// This file is the TypeScript mirror of the SAB ring layout
// shared between the kernel Worker (Rust WASM) and every
// user-process Worker. A Vitest test in
// `web/tests/unit/sab-layout.test.ts` asserts that the values
// here match what the `abi` crate would emit; CI additionally
// runs `cargo run -p xtask -- gen-sab-layout --check` to fail
// loudly if this file is stale.

/* eslint-disable */

export const ABI_MAJOR = 0x1;
export const ABI_MINOR = 0x1;
export const ABI_VERSION: readonly [number, number] = [ABI_MAJOR, ABI_MINOR];

// --- Region offsets ---------------------------------------------------
export const SAB_SIZE = 0x10000;
export const OFF_REQ_HEAD = 0x0;
export const OFF_REQ_TAIL = 0x4;
export const OFF_RES_HEAD = 0x8;
export const OFF_RES_TAIL = 0xC;
export const OFF_USER_WAIT_SLOT = 0x10;
export const OFF_KERNEL_WAIT_SLOT = 0x14;
export const OFF_USER_BLOCK_COUNT = 0x18;
export const OFF_KERNEL_BLOCK_COUNT = 0x1C;
export const OFF_HEADER_FLAGS = 0x20;
export const OFF_REQ_RING = 0x40;
export const REQ_RING_BYTES = 0x3FC0;
export const OFF_RES_RING = 0x4000;
export const RES_RING_BYTES = 0x3FC0;
export const OFF_HEAP_SCRATCH = 0x8000;
export const HEAP_SCRATCH_BYTES = 0x8000;

// --- Slot geometry ----------------------------------------------------
export const SLOT_SIZE = 0x20;
export const REQ_SLOT_COUNT = 0x1FE;
export const RES_SLOT_COUNT = 0x1FE;

// --- Magic wait-slot status values ------------------------------------
export const STATUS_IDLE = 0x0;
export const STATUS_REQUESTED = 0x1;
export const STATUS_SERVICING = 0x2;
export const STATUS_READY = 0x3;

// --- Typed helpers for the TypeScript driver layer --------------------

/** A typed wrapper that exposes the SAB's u32 fields as AtomicInt32Array slots. */
export function sabHeader(sab: SharedArrayBuffer): Int32Array {
  return new Int32Array(sab, 0, OFF_HEAP_SCRATCH / 4);
}

/** The heap scratch region as a Uint8Array for arbitrary payloads. */
export function sabHeapScratch(sab: SharedArrayBuffer): Uint8Array {
  return new Uint8Array(sab, OFF_HEAP_SCRATCH, HEAP_SCRATCH_BYTES);
}
