[package]
name = "display-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "display_server"
path = "src/lib.rs"

[[bin]]
name = "display-server"
path = "src/main.rs"

[dependencies]
abi = { path = "../abi" }
ring = { path = "../ring" }
display-proto = { path = "../display-proto" }
preferences = { path = "../preferences" }
